name: auto-commit

on:
  push

jobs:
  commit:
    permissions: write-all
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: 'kjljixx/gh-actions-test-2'
          token: '${{secrets.ACTIONS_TEST}}'
      - name: Checkout This Repository
        uses: actions/checkout@v4
        with:
          path: 'bsc-2025-raw'
      - name: Download Ordo 1.0
        uses: robinraju/release-downloader@v1
        with:
          repository: 'michiguel/Ordo'
          tag: '1.0'
          fileName: 'ordo-linux64'
      - name: ls
        run: ls
      - name: New File
        run: touch ${{github.sha}}.txt
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: testing
          committer_name: GitHub Actions
          committer_email: actions@github.com
