name: auto-commit

on:
  push

jobs:
  commit:
    permissions: write-all
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout Repository
        uses: EndBug/add-and-commit@v9
        with:
          message: testing
          committer_name: GitHub Actions
          committer_email: actions@github.com
