name: Release

on:
  release

jobs:
  build:
    strategy:
      matrix:
        # Skip macos for now, since ends up with the same filename as ubuntu
        # which means the upload glob needs some more work
        os: ["ubuntu-22.04", "windows-2022"]
        cpu: ["x86-64-v3"]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: g++ test.cpp -o test -O3
        env:
          TARGET_CPU: ${{ matrix.cpu }}
      - name: Upload Assets to Release
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: "test@(|.exe)"
