name: build-for-release

on:
  release:
    types: [published]

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        include:
        - os: "ubuntu-22.04"
          ext: ""
        - os: "windows-2022"
          ext: ".exe"

    runs-on: "${{matrix.os}}"

    steps:
      - uses: actions/checkout@v2
        with:
          toolchain: stable
      - run: "clang++ test.cpp -o aurora-${{github.ref_name}}-${{matrix.os}}${{matrix.ext}} -O3 -march=x86-64-v3"
        env:
          TARGET_CPU: ${{ matrix.cpu }}
      - name: Upload Assets to Release
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["aurora-${{github.ref_name}}-${{matrix.os}}****"]'
